apiVersion: batch/v1
kind: Job
metadata:
  name: "{replaced with MLflow Project name}"
  namespace: kubeflow 
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: "{replaced with MLflow Project name}"
        image: "{replaced with URI of Docker image created during Project execution}"
        command: ["{replaced with MLflow Project entry point command}"]
        volumeMounts:
        - name: "mlruns-volume"
          mountPath: /root/pipeline/kubeflow/notebooks/mlflow/boston/mlruns
      volumes:
      - name: "mlruns-volume"
        hostPath:
          path: "/root/pipeline/kubeflow/notebooks/mlflow/boston/mlruns"
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 256Mi          
