apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: admin
        image: docker.io/pipelineai/admin:1.5.0
        imagePullPolicy: "Always"
        terminationMessagePolicy: "FallbackToLogsOnError"
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            memory: 1Gi
            cpu: 500m
        ports:
        - containerPort: 31996
        volumeMounts:
        env:
        - name: PIPELINE_ADMIN_REQUIRES_AUTH
          value: "True"
        - name: PIPELINE_ADMIN_BASE_PATH
          value: "/admin/app"
        - name: PIPELINE_ADMIN_FEATURE_FLAGS_ON
          value: "auth-enabled,support"
        - name: PIPELINE_ADMIN_FEATURE_FLAGS_OFF
          value: ""
        - name: PIPELINE_ADMIN_HOME_ROUTE
          value: "/"
        - name: PIPELINE_ADMIN_ENV
          value: "production"
        - name: PIPELINE_ADMIN_HOST
          value: "0.0.0.0"
        - name: PIPELINE_ADMIN_PORT
          value: "31996"
        - name: PIPELINE_ADMIN_PROTOCOL
          value: "http"
        - name: PIPELINE_ADMIN_JAEGER_CONFIG_LOGGING
          value: "True"
        - name: PIPELINE_ADMIN_JAEGER_CONFIG_SAMPLER_TYPE
          value: "const"
        - name: PIPELINE_ADMIN_JAEGER_CONFIG_SAMPLER_PARAM
          value: "1"
        - name: PIPELINE_ADMIN_OAUTH_CONFIG_AUTOCLOSE
#  PIPELINE_ADMIN_OAUTH_CONFIG_CLIENT_ID: ""
#  PIPELINE_ADMIN_OAUTH_CONFIG_DOMAIN: "pipelineio.auth0.com"
#  PIPELINE_ADMIN_OAUTH_CONFIG_AUTH_REDIRECT_URL: "/admin/app"
#  PIPELINE_ADMIN_OAUTH_CONFIG_AUTH_RESPONSE_TYPE: "token id_token"
#  PIPELINE_ADMIN_OAUTH_CONFIG_AUTH_PARAMS_SCOPE: "openid profile email"
#  PIPELINE_ADMIN_STRIPE_PUBLIC_KEY: ""
