apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: install-kubeflow
  namespace: kubeflow
spec:
  appdir: /root/pipeline/kubeflow/install-kubeflow
  componentParams:
    ambassador:
    - name: ambassadorServiceType
      value: NodePort
    - name: ambassadorNodePort
      value: "31111"
  components:
  - ambassador
  - argo
  - centraldashboard
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  packages:
  - argo
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pachyderm
  - pipeline
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  repo: /root/pipeline/kubeflow/install-kubeflow/.cache/v0.5.1/kubeflow
  useBasicAuth: false
  useIstio: true
  version: v0.5.1
status: {}
