apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: jupyter-web-app
  name: jupyter-notebook-clusterrole-binding
  #  namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jupyter-notebook-role
subjects:
- kind: ServiceAccount
  name: jupyter-notebook
  namespace: kubeflow
